# .streamlit/secrets.toml
# Armazenamento SEGURO das chaves para a aplicação web

GEMINI_API_KEY = "AIzaSyC3BAiye6glPoLJn58pAbpd5oFopAVh6xo"

[supabase]
URL = "https://sdqqwkavtddgklbkocob.supabase.co"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkcXF3a2F2dGRkZ2tsYmtvY29iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTM2MTczNSwiZXhwIjoyMDc0OTM3NzM1fQ.Wu1XpGPq86Z-tRVBGAQq54wWMJoZoCQ2V_DNrg7INhw"
TABLE_NAME = "champlim"
